### ISSUE TITLE
9.0 version incorrectly merged onto 8.0

### ISSUE THREAD

**Issue by thomaspaulb** [Openworx/odoo-addons#5]
@mgielissen Unfortunately a mistake happened, the 8.0 port to new API from @nzaterrence was merged but the [9.0 port was mistakenly merged to the 8.0 branch also](https://github.com/Openworx/odoo-addons/pull/4).

What should have happened instead is that you create a new 9.0 branch in the repository and merge with that one. For now, can you revert the [8.0 branch](https://github.com/Openworx/odoo-addons/commits/8.0) to commit [bbd71d04c73bab9eda31bda9a3eb629696942204](https://github.com/Openworx/odoo-addons/commit/bbd71d04c73bab9eda31bda9a3eb629696942204)?

**Comment by mgielissen** [comment]
kvk version incorrect, changed from 9 to 8
