### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by acidjunk** [Openworx/odoo-addons#8]
Please choose a license so people/users know what they can/can't do with this software.

**Comment by acidjunk** [comment]
ah, a license in the.py files itself: LGPL-V3 -> probably better to put the (complete)license also in the top folders of the modules.

**Comment by mgielissen** [comment]
The manifest file contains the license:

"license": "LGPL-3",

**Comment by acidjunk** [comment]
Module looks promising.

If you put it in the folders a LICENSE.txt -> you don't have to put it in other files. (probably wouldn't hurt to run flake8 on your code). Let me know if you need help with code style and/or tests.

**Comment by mgielissen** [comment]
License.txt is added.
